<template>
  <div>
    <div>
    <header>
      <h1></h1>
    </header>
  </div>
  <br>
    <input type="text" v-model="searchQuery" placeholder="Buscar Pokémon">
    <div class="pokedex">
      <div v-for="pokemon in filteredPokemonList" :key="pokemon.id" class="pokemon">
        <img :src="pokemon.image" :alt="pokemon.name">
        <p>{{ pokemon.name }}</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      searchQuery: '',
      pokemonList: [
      { id: 1, name: 'Bulbasur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', type: ['Grass', 'Poison'] },
  { id: 2, name: 'Ivysaur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', type: ['Grass', 'Poison'] },
  { id: 3, name: 'Venusaur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', type: ['Grass', 'Poison'] },
  { id: 4, name: 'Charmander', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', type: ['Fire'] },
  { id: 5, name: 'Charmeleon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', type: ['Fire'] },
  { id: 6, name: 'Charizard', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', type: ['Fire', 'Flying'] },
  { id: 7, name: 'Squirtle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', type: ['Water'] },
  { id: 8, name: 'Wartortle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', type: ['Water'] },
  { id: 9, name: 'Blastoise', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', type: ['Water'] },
  { id: 10, name: 'Caterpie', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', type: ['Bug'] },
  { id: 11, name: 'Metapod', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', type: ['Bug'] },
  { id: 12, name: 'Butterfree', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', type: ['Bug', 'Flying'] },
  { id: 13, name: 'Weedle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', type: ['Bug', 'Poison'] },
  { id: 14, name: 'Kakuna', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', type: ['Bug', 'Poison'] },
  { id: 15, name: 'Beedrill', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', type: ['Bug', 'Poison'] },
  { id: 16, name: 'Pidgey', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', type: ['Normal', 'Flying'] },
  { id: 17, name: 'Pidgeotto', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', type: ['Normal', 'Flying'] },
  { id: 18, name: 'Pidgeot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', type: ['Normal', 'Flying'] },
  { id: 19, name: 'Rattata', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', type: ['Normal'] },
  { id: 20, name: 'Raticate', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', type: ['Normal'] },
  { id: 21, name: 'Spearow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', type: ['Normal', 'Flying'] },
  { id: 22, name: 'Fearow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', type: ['Normal', 'Flying'] },
  { id: 23, name: 'Ekans', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', type: ['Poison'] },
  { id: 24, name: 'Arbok', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', type: ['Poison'] },
  { id: 25, name: 'Pikachu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', type: ['Electric'] },
  { id: 26, name: 'Raichu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png', type: ['Electric'] },
  { id: 27, name: 'Sandshrew', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png', type: ['Ground'] },
  { id: 28, name: 'Sandslash', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png', type: ['Ground'] },
  { id: 29, name: 'Nidoran♀', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', type: ['Poison'] },
  { id: 30, name: 'Nidorina', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', type: ['Poison'] },
  { id: 31, name: 'Nidoqueen', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', type: ['Poison', 'Ground'] },
  { id: 32, name: 'Nidoran♂', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', type: ['Poison'] },
  { id: 33, name: 'Nidorino', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', type: ['Poison'] },
  { id: 34, name: 'Nidoking', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png', type: ['Poison', 'Ground'] },
  { id: 35, name: 'Clefairy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png', type: ['Fairy'] },
  { id: 36, name: 'Clefable', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png', type: ['Fairy'] },
  { id: 37, name: 'Vulpix', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', type: ['Fire'] },
  { id: 38, name: 'Ninetales', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', type: ['Fire'] },
  { id: 39, name: 'Jigglypuff', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png', type: ['Normal', 'Fairy'] },
  { id: 40, name: 'Wigglytuff', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png', type: ['Normal', 'Fairy'] },
  { id: 41, name: 'Zubat', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png', type: ['Poison', 'Flying'] },
  { id: 42, name: 'Golbat', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png', type: ['Poison', 'Flying'] },
  { id: 43, name: 'Oddish', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png', type: ['Grass', 'Poison'] },
  { id: 44, name: 'Gloom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png', type: ['Grass', 'Poison'] },
  { id: 45, name: 'Vileplume', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png', type: ['Grass', 'Poison'] },
  { id: 46, name: 'Paras', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png', type: ['Bug', 'Grass'] },
  { id: 47, name: 'Parasect', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png', type: ['Bug', 'Grass'] },
  { id: 48, name: 'Venonat', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png', type: ['Bug', 'Poison'] },
  { id: 49, name: 'Venomoth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png', type: ['Bug', 'Poison'] },
  { id: 50, name: 'Diglett', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png', type: ['Ground'] },
  { id: 51, name: 'Dugtrio', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png', type: ['Ground'] },
  { id: 52, name: 'Meowth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png', type: ['Normal'] },
  { id: 53, name: 'Persian', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png', type: ['Normal'] },
  { id: 54, name: 'Psyduck', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png', type: ['Water'] },
  { id: 55, name: 'Golduck', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png', type: ['Water'] },
  { id: 56, name: 'Mankey', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png', type: ['Fighting'] },
  { id: 57, name: 'Primeape', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png', type: ['Fighting'] },
  { id: 58, name: 'Growlithe', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png', type: ['Fire'] },
  { id: 59, name: 'Arcanine', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png', type: ['Fire'] },
  { id: 60, name: 'Poliwag', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png', type: ['Water'] },
  { id: 61, name: 'Poliwhirl', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png', type: ['Water'] },
  { id: 62, name: 'Poliwrath', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png', type: ['Water', 'Fighting'] },
  { id: 63, name: 'Abra', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png', type: ['Psychic'] },
  { id: 64, name: 'Kadabra', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png', type: ['Psychic'] },
  { id: 65, name: 'Alakazam', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png', type: ['Psychic'] },
  { id: 66, name: 'Machop', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png', type: ['Fighting'] },
  { id: 67, name: 'Machoke', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png', type: ['Fighting'] },
  { id: 68, name: 'Machamp', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png', type: ['Fighting'] },
  { id: 69, name: 'Bellsprout', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png', type: ['Grass', 'Poison'] },
  { id: 70, name: 'Weepinbell', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png', type: ['Grass', 'Poison'] },
  { id: 71, name: 'Victreebel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png', type: ['Grass', 'Poison'] },
  { id: 72, name: 'Tentacool', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png', type: ['Water', 'Poison'] },
  { id: 73, name: 'Tentacruel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png', type: ['Water', 'Poison'] },
  { id: 74, name: 'Geodude', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png', type: ['Rock', 'Ground'] },
  { id: 75, name: 'Graveler', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png', type: ['Rock', 'Ground'] },
  { id: 76, name: 'Golem', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png', type: ['Rock', 'Ground'] },
  { id: 77, name: 'Ponyta', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', type: ['Fire'] },
  { id: 78, name: 'Rapidash', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png', type: ['Fire'] },
  { id: 79, name: 'Slowpoke', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png', type: ['Water', 'Psychic'] },
  { id: 80, name: 'Slowbro', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png', type: ['Water', 'Psychic'] },
  { id: 81, name: 'Magnemite', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png', type: ['Electric', 'Steel'] },
  { id: 82, name: 'Magneton', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png', type: ['Electric', 'Steel'] },
  { id: 83, name: 'Farfetch\'d', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png', type: ['Normal', 'Flying'] },
  { id: 84, name: 'Doduo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png', type: ['Normal', 'Flying'] },
  { id: 85, name: 'Dodrio', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png', type: ['Normal', 'Flying'] },
  { id: 86, name: 'Seel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png', type: ['Water'] },
  { id: 87, name: 'Dewgong', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png', type: ['Water', 'Ice'] },
  { id: 88, name: 'Grimer', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png', type: ['Poison'] },
  { id: 89, name: 'Muk', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png', type: ['Poison'] },
  { id: 90, name: 'Shellder', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png', type: ['Water'] },
  { id: 91, name: 'Cloyster', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png', type: ['Water', 'Ice'] },
  { id: 92, name: 'Gastly', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png', type: ['Ghost', 'Poison'] },
  { id: 93, name: 'Haunter', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png', type: ['Ghost', 'Poison'] },
  { id: 94, name: 'Gengar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png', type: ['Ghost', 'Poison'] },
  { id: 95, name: 'Onix', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png', type: ['Rock', 'Ground'] },
  { id: 96, name: 'Drowzee', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png', type: ['Psychic'] },
  { id: 97, name: 'Hypno', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png', type: ['Psychic'] },
  { id: 98, name: 'Krabby', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png', type: ['Water'] },
  { id: 99, name: 'Kingler', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png', type: ['Water'] },
  { id: 100, name: 'Voltorb', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png', type: ['Electric'] },
  { id: 101, name: 'Electrode', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png', type: ['Electric'] },
  { id: 102, name: 'Exeggcute', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png', type: ['Grass', 'Psychic'] },
  { id: 103, name: 'Exeggutor', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png', type: ['Grass', 'Psychic'] },
  { id: 104, name: 'Cubone', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png', type: ['Ground'] },
  { id: 105, name: 'Marowak', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png', type: ['Ground'] },
  { id: 106, name: 'Hitmonlee', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png', type: ['Fighting'] },
  { id: 107, name: 'Hitmonchan', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png', type: ['Fighting'] },
  { id: 108, name: 'Lickitung', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png', type: ['Normal'] },
  { id: 109, name: 'Koffing', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png', type: ['Poison'] },
  { id: 110, name: 'Weezing', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png', type: ['Poison'] },
  { id: 111, name: 'Rhyhorn', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png', type: ['Ground', 'Rock'] },
  { id: 112, name: 'Rhydon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png', type: ['Ground', 'Rock'] },
  { id: 113, name: 'Chansey', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png', type: ['Normal'] },
  { id: 114, name: 'Tangela', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png', type: ['Grass'] },
  { id: 115, name: 'Kangaskhan', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png', type: ['Normal'] },
  { id: 116, name: 'Horsea', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png', type: ['Water'] },
  { id: 117, name: 'Seadra', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png', type: ['Water'] },
  { id: 118, name: 'Goldeen', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png', type: ['Water'] },
  { id: 119, name: 'Seaking', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png', type: ['Water'] },
  { id: 120, name: 'Staryu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png', type: ['Water'] },
  { id: 121, name: 'Starmie', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png', type: ['Water', 'Psychic'] },
  { id: 122, name: 'Mr. Mime', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png', type: ['Psychic', 'Fairy'] },
  { id: 123, name: 'Scyther', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png', type: ['Bug', 'Flying'] },
  { id: 124, name: 'Jynx', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png', type: ['Ice', 'Psychic'] },
  { id: 125, name: 'Electabuzz', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png', type: ['Electric'] },
  { id: 126, name: 'Magmar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png', type: ['Fire'] },
  { id: 127, name: 'Pinsir', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png', type: ['Bug'] },
  { id: 128, name: 'Tauros', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png', type: ['Normal'] },
  { id: 129, name: 'Magikarp', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png', type: ['Water'] },
  { id: 130, name: 'Gyarados', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png', type: ['Water', 'Flying'] },
  { id: 131, name: 'Lapras', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png', type: ['Water', 'Ice'] },
  { id: 132, name: 'Ditto', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png', type: ['Normal'] },
  { id: 133, name: 'Eevee', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png', type: ['Normal'] },
  { id: 134, name: 'Vaporeon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png', type: ['Water'] },
  { id: 135, name: 'Jolteon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png', type: ['Electric'] },
  { id: 136, name: 'Flareon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png', type: ['Fire'] },
  { id: 137, name: 'Porygon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png', type: ['Normal'] },
  { id: 138, name: 'Omanyte', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png', type: ['Rock', 'Water'] },
  { id: 139, name: 'Omastar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png', type: ['Rock', 'Water'] },
  { id: 140, name: 'Kabuto', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png', type: ['Rock', 'Water'] },
  { id: 141, name: 'Kabutops', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png', type: ['Rock', 'Water'] },
  { id: 142, name: 'Aerodactyl', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png', type: ['Rock', 'Flying'] },
  { id: 143, name: 'Snorlax', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png', type: ['Normal'] },
  { id: 144, name: 'Articuno', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png', type: ['Ice', 'Flying'] },
  { id: 145, name: 'Zapdos', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png', type: ['Electric', 'Flying'] },
  { id: 146, name: 'Moltres', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png', type: ['Fire', 'Flying'] },
  { id: 147, name: 'Dratini', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png', type: ['Dragon'] },
  { id: 148, name: 'Dragonair', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png', type: ['Dragon'] },
  { id: 149, name: 'Dragonite', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png', type: ['Dragon', 'Flying'] },
  { id: 150, name: 'Mewtwo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png', type: ['Psychic'] },
  { id: 151, name: 'Mew', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png', type: ['Psychic']} ,
        { id: 152, name: 'Chikorita', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/152.png' },
        { id: 153, name: 'Bayleef', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/153.png' },
        { id: 154, name: 'Meganium', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/154.png' },
        { id: 155, name: 'Cyndaquil', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/155.png' },
        { id: 156, name: 'Quilava', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/156.png' },
        { id: 157, name: 'Typhlosion', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/157.png' },
        { id: 158, name: 'Totodile', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/158.png' },
        { id: 159, name: 'Croconaw', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/159.png' },
        { id: 160, name: 'Feraligatr', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/160.png' },
        { id: 161, name: 'Sentret', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/161.png' },
        { id: 162, name: 'Furret', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/162.png' },
        { id: 163, name: 'Hoothoot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/163.png' },
        { id: 164, name: 'Noctowl', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/164.png' },
        { id: 165, name: 'Ledyba', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/165.png' },
        { id: 166, name: 'Ledian', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/166.png' },
        { id: 167, name: 'Spinarak', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/167.png' },
        { id: 168, name: 'Ariados', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/168.png' },
        { id: 169, name: 'Crobat', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/169.png' },
        { id: 170, name: 'Chinchou', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/170.png' },
        { id: 171, name: 'Lanturn', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/171.png' },
        { id: 172, name: 'Pichu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/172.png' },
        { id: 173, name: 'Cleffa', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/173.png' },
        { id: 174, name: 'Igglybuff', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/174.png' },
        { id: 175, name: 'Togepi', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/175.png' },
        { id: 176, name: 'Togetic', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/176.png' },
        { id: 177, name: 'Natu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/177.png' },
        { id: 178, name: 'Xatu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/178.png' },
        { id: 179, name: 'Mareep', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/179.png' },
        { id: 180, name: 'Flaaffy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/180.png' },
        { id: 181, name: 'Ampharos', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/181.png' },
        { id: 182, name: 'Bellossom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/182.png' },
        { id: 183, name: 'Marill', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/183.png' },
        { id: 184, name: 'Azumarill', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/184.png' },
        { id: 185, name: 'Sudowoodo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/185.png' },
        { id: 186, name: 'Politoed', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/186.png' },
        { id: 187, name: 'Hoppip', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/187.png' },
        { id: 188, name: 'Skiploom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/188.png' },
        { id: 189, name: 'Jumpluff', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/189.png' },
        { id: 190, name: 'Aipom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/190.png' },
        { id: 191, name: 'Sunkern', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/191.png' },
        { id: 192, name: 'Sunflora', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/192.png' },
        { id: 193, name: 'Yanma', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/193.png' },
        { id: 194, name: 'Wooper', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/194.png' },
        { id: 195, name: 'Quagsire', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/195.png' },
        { id: 196, name: 'Espeon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png' },
        { id: 197, name: 'Umbreon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png' },
        { id: 198, name: 'Murkrow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/198.png' },
        { id: 199, name: 'Slowking', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/199.png' },
        { id: 200, name: 'Misdreavus', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/200.png' },
        { id: 201, name: 'Unown', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/201.png' },
        { id: 202, name: 'Wobbuffet', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/202.png' },
        { id: 203, name: 'Girafarig', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/203.png' },
        { id: 204, name: 'Pineco', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/204.png' },
        { id: 205, name: 'Forretress', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/205.png' },
        { id: 206, name: 'Dunsparce', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/206.png' },
        { id: 207, name: 'Gligar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/207.png' },
        { id: 208, name: 'Steelix', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/208.png' },
        { id: 209, name: 'Snubbull', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/209.png' },
        { id: 210, name: 'Granbull', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/210.png' },
        { id: 211, name: 'Qwilfish', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/211.png' },
        { id: 212, name: 'Scizor', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/212.png' },
        { id: 213, name: 'Shuckle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/213.png' },
        { id: 214, name: 'Heracross', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/214.png' },
        { id: 215, name: 'Sneasel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png' },
        { id: 216, name: 'Teddiursa', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/216.png' },
        { id: 217, name: 'Ursaring', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/217.png' },
        { id: 218, name: 'Slugma', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/218.png' },
        { id: 219, name: 'Magcargo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/219.png' },
        { id: 220, name: 'Swinub', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png' },
        { id: 221, name: 'Piloswine', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/221.png' },
        { id: 222, name: 'Corsola', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/222.png' },
        { id: 223, name: 'Remoraid', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/223.png' },
        { id: 224, name: 'Octillery', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/224.png' },
        { id: 225, name: 'Delibird', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png' },
        { id: 226, name: 'Mantine', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/226.png' },
        { id: 227, name: 'Skarmory', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png' },
        { id: 228, name: 'Houndour', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/228.png' },
        { id: 229, name: 'Houndoom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/229.png' },
        { id: 230, name: 'Kingdra', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png' },
        { id: 231, name: 'Phanpy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/231.png' },
        { id: 232, name: 'Donphan', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/232.png' },
        { id: 233, name: 'Porygon2', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/233.png' },
        { id: 234, name: 'Stantler', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/234.png' },
        { id: 235, name: 'Smeargle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/235.png' },
        { id: 236, name: 'Tyrogue', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/236.png' },
        { id: 237, name: 'Hitmontop', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/237.png' },
        { id: 238, name: 'Smoochum', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/238.png' },
        { id: 239, name: 'Elekid', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/239.png' },
        { id: 240, name: 'Magby', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/240.png' },
        { id: 241, name: 'Miltank', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/241.png' },
        { id: 242, name: 'Blissey', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/242.png' },
        { id: 243, name: 'Raikou', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/243.png' },
        { id: 244, name: 'Entei', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/244.png' },
        { id: 245, name: 'Suicune', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/245.png' },
        { id: 246, name: 'Larvitar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png' },
        { id: 247, name: 'Pupitar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/247.png' },
        { id: 248, name: 'Tyranitar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png' },
        { id: 249, name: 'Lugia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/249.png' },
        { id: 250, name: 'Ho-Oh', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/250.png' },
        { id: 251, name: 'Celebi', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/251.png' },
        { id: 252, name: 'Treecko', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png' },
        { id: 253, name: 'Grovyle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/253.png' },
        { id: 254, name: 'Sceptile', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/254.png' },
        { id: 255, name: 'Torchic', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png' },
        { id: 256, name: 'Combusken', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png' },
        { id: 257, name: 'Blaziken', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/257.png' },
        { id: 258, name: 'Mudkip', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png' },
        { id: 259, name: 'Marshtomp', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/259.png' },
        { id: 260, name: 'Swampert', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png' },
        { id: 261, name: 'Poochyena', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/261.png' },
        { id: 262, name: 'Mightyena', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/262.png' },
        { id: 263, name: 'Zigzagoon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/263.png' },
        { id: 264, name: 'Linoone', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/264.png' },
        { id: 265, name: 'Wurmple', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/265.png' },
        { id: 266, name: 'Silcoon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/266.png' },
        { id: 267, name: 'Beautifly', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/267.png' },
        { id: 268, name: 'Cascoon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/268.png' },
        { id: 269, name: 'Dustox', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/269.png' },
        { id: 270, name: 'Lotad', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/270.png' },
        { id: 271, name: 'Lombre', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/271.png' },
        { id: 272, name: 'Ludicolo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/272.png' },
        { id: 273, name: 'Seedot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/273.png' },
        { id: 274, name: 'Nuzleaf', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/274.png' },
        { id: 275, name: 'Shiftry', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/275.png' },
        { id: 276, name: 'Taillow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/276.png' },
        { id: 277, name: 'Swellow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/277.png' },
        { id: 278, name: 'Wingull', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/278.png' },
        { id: 279, name: 'Pelipper', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/279.png' },
        { id: 280, name: 'Ralts', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/280.png' },
        { id: 281, name: 'Kirlia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/281.png' },
        { id: 282, name: 'Gardevoir', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png' },
        { id: 283, name: 'Surskit', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/283.png' },
        { id: 284, name: 'Masquerain', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/284.png' },
        { id: 285, name: 'Shroomish', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/285.png' },
        { id: 286, name: 'Breloom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/286.png' },
        { id: 287, name: 'Slakoth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/287.png' },
        { id: 288, name: 'Vigoroth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/288.png' },
        { id: 289, name: 'Slaking', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/289.png' },
        { id: 290, name: 'Nincada', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/290.png' },
        { id: 291, name: 'Ninjask', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/291.png' },
        { id: 292, name: 'Shedinja', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/292.png' },
        { id: 293, name: 'Whismur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/293.png' },
        { id: 294, name: 'Loudred', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/294.png' },
        { id: 295, name: 'Exploud', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/295.png' },
        { id: 296, name: 'Makuhita', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/296.png' },
        { id: 297, name: 'Hariyama', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/297.png' },
        { id: 298, name: 'Azurill', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/298.png' },
        { id: 299, name: 'Nosepass', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/299.png' },
        { id: 300, name: 'Skitty', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/300.png' },
        { id: 301, name: 'Delcatty', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/301.png' },
        { id: 302, name: 'Sableye', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/302.png' },
        { id: 303, name: 'Mawile', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/303.png' },
        { id: 304, name: 'Aron', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/304.png' },
        { id: 305, name: 'Lairon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/305.png' },
        { id: 306, name: 'Aggron', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/306.png' },
        { id: 307, name: 'Meditite', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/307.png' },
        { id: 308, name: 'Medicham', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/308.png' },
        { id: 309, name: 'Electrike', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/309.png' },
        { id: 310, name: 'Manectric', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/310.png' },
        { id: 311, name: 'Plusle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/311.png' },
        { id: 312, name: 'Minun', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/312.png' },
        { id: 313, name: 'Volbeat', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/313.png' },
        { id: 314, name: 'Illumise', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/314.png' },
        { id: 315, name: 'Roselia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/315.png' },
        { id: 316, name: 'Gulpin', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/316.png' },
        { id: 317, name: 'Swalot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/317.png' },
        { id: 318, name: 'Carvanha', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/318.png' },
        { id: 319, name: 'Sharpedo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/319.png' },
        { id: 320, name: 'Wailmer', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/320.png' },
        { id: 321, name: 'Wailord', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/321.png' },
        { id: 322, name: 'Numel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/322.png' },
        { id: 323, name: 'Camerupt', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/323.png' },
        { id: 324, name: 'Torkoal', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/324.png' },
        { id: 325, name: 'Spoink', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/325.png' },
        { id: 326, name: 'Grumpig', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/326.png' },
        { id: 327, name: 'Spinda', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/327.png' },
        { id: 328, name: 'Trapinch', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/328.png' },
        { id: 329, name: 'Vibrava', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/329.png' },
        { id: 330, name: 'Flygon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/330.png' },
        { id: 331, name: 'Cacnea', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/331.png' },
        { id: 332, name: 'Cacturne', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/332.png' },
        { id: 333, name: 'Swablu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/333.png' },
        { id: 334, name: 'Altaria', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/334.png' },
        { id: 335, name: 'Zangoose', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/335.png' },
        { id: 336, name: 'Seviper', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/336.png' },
        { id: 337, name: 'Lunatone', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/337.png' },
        { id: 338, name: 'Solrock', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/338.png' },
        { id: 339, name: 'Barboach', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/339.png' },
        { id: 340, name: 'Whiscash', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/340.png' },
        { id: 341, name: 'Corphish', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/341.png' },
        { id: 342, name: 'Crawdaunt', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/342.png' },
        { id: 343, name: 'Baltoy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/343.png' },
        { id: 344, name: 'Claydol', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/344.png' },
        { id: 345, name: 'Lileep', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/345.png' },
        { id: 346, name: 'Cradily', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/346.png' },
        { id: 347, name: 'Anorith', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/347.png' },
        { id: 348, name: 'Armaldo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/348.png' },
        { id: 349, name: 'Feebas', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/349.png' },
        { id: 350, name: 'Milotic', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/350.png' },
        { id: 351, name: 'Castform', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/351.png' },
        { id: 352, name: 'Kecleon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/352.png' },
        { id: 353, name: 'Shuppet', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/353.png' },
        { id: 354, name: 'Banette', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/354.png' },
        { id: 355, name: 'Duskull', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/355.png' },
        { id: 356, name: 'Dusclops', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/356.png' },
        { id: 357, name: 'Tropius', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/357.png' },
        { id: 358, name: 'Chimecho', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/358.png' },
        { id: 359, name: 'Absol', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/359.png' },
        { id: 360, name: 'Wynaut', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/360.png' },
        { id: 361, name: 'Snorunt', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/361.png' },
        { id: 362, name: 'Glalie', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/362.png' },
        { id: 363, name: 'Spheal', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/363.png' },
        { id: 364, name: 'Sealeo', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/364.png' },
        { id: 365, name: 'Walrein', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/365.png' },
        { id: 366, name: 'Clamperl', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/366.png' },
        { id: 367, name: 'Huntail', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/367.png' },
        { id: 368, name: 'Gorebyss', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/368.png' },
        { id: 369, name: 'Relicanth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/369.png' },
        { id: 370, name: 'Luvdisc', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/370.png' },
        { id: 371, name: 'Bagon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/371.png' },
        { id: 372, name: 'Shelgon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/372.png' },
        { id: 373, name: 'Salamence', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/373.png' },
        { id: 374, name: 'Beldum', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/374.png' },
        { id: 375, name: 'Metang', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/375.png' },
        { id: 376, name: 'Metagross', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/376.png' },
        { id: 377, name: 'Regirock', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/377.png' },
        { id: 378, name: 'Regice', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/378.png' },
        { id: 379, name: 'Registeel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/379.png' },
        { id: 380, name: 'Latias', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/380.png' },
        { id: 381, name: 'Latios', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/381.png' },
        { id: 382, name: 'Kyogre', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/382.png' },
        { id: 383, name: 'Groudon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/383.png' },
        { id: 384, name: 'Rayquaza', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png' },
        { id: 385, name: 'Jirachi', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/385.png' },
        { id: 386, name: 'Deoxys', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/386.png' },
        { id: 387, name: 'Turtwig', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/387.png' },
  { id: 388, name: 'Grotle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/388.png' },
  { id: 389, name: 'Torterra', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/389.png' },
  { id: 390, name: 'Chimchar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/390.png' },
  { id: 391, name: 'Monferno', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/391.png' },
  { id: 392, name: 'Infernape', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png' },
  { id: 393, name: 'Piplup', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/393.png' },
  { id: 394, name: 'Prinplup', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/394.png' },
  { id: 395, name: 'Empoleon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/395.png' },
  { id: 396, name: 'Starly', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/396.png' },
  { id: 397, name: 'Staravia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/397.png' },
  { id: 398, name: 'Staraptor', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/398.png' },
  { id: 399, name: 'Bidoof', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/399.png' },
  { id: 400, name: 'Bibarel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/400.png' },
  { id: 401, name: 'Kricketot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/401.png' },
  { id: 402, name: 'Kricketune', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/402.png' },
  { id: 403, name: 'Shinx', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/403.png' },
  { id: 404, name: 'Luxio', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/404.png' },
  { id: 405, name: 'Luxray', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/405.png' },
  { id: 406, name: 'Budew', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/406.png' },
  { id: 407, name: 'Roserade', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/407.png' },
  { id: 408, name: 'Cranidos', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/408.png' },
  { id: 409, name: 'Rampardos', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/409.png' },
  { id: 410, name: 'Shieldon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/410.png' },
  { id: 411, name: 'Bastiodon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/411.png' },
  { id: 412, name: 'Burmy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/412.png' },
  { id: 413, name: 'Wormadam', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/413.png' },
  { id: 414, name: 'Mothim', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/414.png' },
  { id: 415, name: 'Combee', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/415.png' },
  { id: 416, name: 'Vespiquen', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/416.png' },
  { id: 417, name: 'Pachirisu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/417.png' },
  { id: 418, name: 'Buizel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/418.png' },
  { id: 419, name: 'Floatzel', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/419.png' },
  { id: 420, name: 'Cherubi', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/420.png' },
  { id: 421, name: 'Cherrim', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/421.png' },
  { id: 422, name: 'Shellos', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/422.png' },
  { id: 423, name: 'Gastrodon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/423.png' },
  { id: 424, name: 'Ambipom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/424.png' },
  { id: 425, name: 'Drifloon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/425.png' },
  { id: 426, name: 'Drifblim', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/426.png' },
  { id: 427, name: 'Buneary', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/427.png' },
  { id: 428, name: 'Lopunny', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/428.png' },
  { id: 429, name: 'Mismagius', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/429.png' },
  { id: 430, name: 'Honchkrow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/430.png' },
  { id: 431, name: 'Glameow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/431.png' },
  { id: 432, name: 'Purugly', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/432.png' },
  { id: 433, name: 'Chingling', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/433.png' },
  { id: 434, name: 'Stunky', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/434.png' },
  { id: 435, name: 'Skuntank', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/435.png' },
  { id: 436, name: 'Bronzor', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/436.png' },
  { id: 437, name: 'Bronzong', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/437.png' },
  { id: 438, name: 'Bonsly', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/438.png' },
  { id: 439, name: 'Mime Jr.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/439.png' },
  { id: 440, name: 'Happiny', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/440.png' },
  { id: 441, name: 'Chatot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/441.png' },
  { id: 442, name: 'Spiritomb', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/442.png' },
  { id: 443, name: 'Gible', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/443.png' },
  { id: 444, name: 'Gabite', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/444.png' },
  { id: 445, name: 'Garchomp', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/445.png' },
  { id: 446, name: 'Munchlax', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/446.png' },
  { id: 447, name: 'Riolu', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/447.png' },
  { id: 448, name: 'Lucario', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png' },
  { id: 449, name: 'Hippopotas', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/449.png' },
  { id: 450, name: 'Hippowdon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/450.png' },
  { id: 451, name: 'Skorupi', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/451.png' },
  { id: 452, name: 'Drapion', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/452.png' },
  { id: 453, name: 'Croagunk', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/453.png' },
  { id: 454, name: 'Toxicroak', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/454.png' },
  { id: 455, name: 'Carnivine', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/455.png' },
  { id: 456, name: 'Finneon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/456.png' },
  { id: 457, name: 'Lumineon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/457.png' },
  { id: 458, name: 'Mantyke', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/458.png' },
  { id: 459, name: 'Snover', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/459.png' },
  { id: 460, name: 'Abomasnow', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/460.png' },
  { id: 461, name: 'Weavile', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/461.png' },
  { id: 462, name: 'Magnezone', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/462.png' },
  { id: 463, name: 'Lickilicky', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/463.png' },
  { id: 464, name: 'Rhyperior', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/464.png' },
  { id: 465, name: 'Tangrowth', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/465.png' },
  { id: 466, name: 'Electivire', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/466.png' },
  { id: 467, name: 'Magmortar', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/467.png' },
  { id: 468, name: 'Togekiss', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/468.png' },
  { id: 469, name: 'Yanmega', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/469.png' },
  { id: 470, name: 'Leafeon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/470.png' },
  { id: 471, name: 'Glaceon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/471.png' },
  { id: 472, name: 'Gliscor', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/472.png' },
  { id: 473, name: 'Mamoswine', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/473.png' },
  { id: 474, name: 'Porygon-Z', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/474.png' },
  { id: 475, name: 'Gallade', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/475.png' },
  { id: 476, name: 'Probopass', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/476.png' },
  { id: 477, name: 'Dusknoir', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/477.png' },
  { id: 478, name: 'Froslass', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/478.png' },
  { id: 479, name: 'Rotom', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/479.png' },
  { id: 480, name: 'Uxie', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/480.png' },
  { id: 481, name: 'Mesprit', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/481.png' },
  { id: 482, name: 'Azelf', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/482.png' },
  { id: 483, name: 'Dialga', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/483.png' },
  { id: 484, name: 'Palkia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/484.png' },
  { id: 485, name: 'Heatran', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/485.png' },
  { id: 486, name: 'Regigigas', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/486.png' },
  { id: 487, name: 'Giratina', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/487.png' },
  { id: 488, name: 'Cresselia', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/488.png' },
  { id: 489, name: 'Phione', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/489.png' },
  { id: 490, name: 'Manaphy', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/490.png' },
  { id: 491, name: 'Darkrai', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/491.png' },
  { id: 492, name: 'Shaymin', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/492.png' },
  { id: 493, name: 'Arceus', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493.png' }



      ]
    };
  },
  computed: {
    filteredPokemonList() {
      return this.pokemonList.filter(pokemon =>
        pokemon.name.toLowerCase().includes(this.searchQuery.toLowerCase())
      );
    }
  },
  methods: {
  showPokemonType(pokemon) {
    const types = pokemon.type.join(' and ');
    alert(`The type of ${pokemon.name} is ${types}`);
  }
  },
  // Function to fetch Pokemon data
  async fetchPokemon(pokemonName) {
    try {
      const response = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemonName}`);
      const pokemonData = await response.json();
      return pokemonData;
    } catch (error) {
      console.log('Error fetching Pokemon data:', error);
    }
  }
}


</script>

<style scoped>
.pokedex {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 20px;
  background-color: white;
}

header {
  background-color: #ffcc00;
  padding: 5% ;
  text-align: center;
  color: #fff;
}

.pokemon {
  text-align: center;
}
footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 20px;
  }
</style>
